import './globals.css'
import { Inter } from 'next/font/google'
import ReactQueryProvider from './react-query-provider'
import { Modal } from '@/components/modal/Modal'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Shop',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<ReactQueryProvider>
			<html lang="en">
				<body className={inter.className}>{children}</body>
			</html>
		</ReactQueryProvider>
	)
}
