import '../globals.css'
import Header from '@/components/Header'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

import StoreProvider from '@/store/provider'

export const metadata = {
	title: 'Shop',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<StoreProvider>
					<Header />
				</StoreProvider>
				<main className="px-10 my-6 max-w-[1500px] m-auto">{children}</main>
			</body>
		</html>
	)
}
