import Link from 'next/link'
import '../globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

import StoreProvider from '@/redux/provider'

export const metadata = {
	title: 'Authorization',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main className="flex flex-col items-center gap-6 px-10 mt-6">
					<Link href="/" className="font-bold text-3xl">
						SHOP
					</Link>
					<div className="w-[440px] flex flex-col gap-4">
						<StoreProvider>{children}</StoreProvider>
					</div>
				</main>
			</body>
		</html>
	)
}
